### ISSUE TITLE
Persona command doesn't require any permissions and can be used by anybody.

### ISSUE THREAD

**Issue by SeveralCircles** [SeveralCircles/colors#8]

**Comment by SeveralCircles** [comment]
@Minotaurinmaze any progress on this issue?

**Comment by Minotaurinmaze** [comment]
Should be fixed. I added this code https://github.com/SeveralCircles/colors/commit/e90e38fccc2deb6cfa632220a123f8b0a2f438cc that hopefully works.

**Comment by SeveralCircles** [comment]
The code in e90e38f would actually cause the command to work only if the player does not have permission. Remove the `!` before `hasPermission` and you should be good.

**Comment by Minotaurinmaze** [comment]
https://github.com/SeveralCircles/colors/commit/a6d1193a6e94460f6da22d0e68b8b0640f743079 should have fixed the issue.

**Comment by SeveralCircles** [comment]
Issue resolved with a6d1193.
